name: eliman
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/tire_change.jpg
    - assets/images/house_lockout.jpg
    - assets/images/lock_installation.jpg
    - assets/images/tv_mounting.jpg
    - assets/images/furniture_assembly.jpg
    - assets/images/packing.jpg
    - assets/images/washer_repair.jpg
    - assets/images/full_apartment_move.jpg
    - assets/images/car_lockout.jpg
    - assets/images/standard_cleaning.jpg
    - assets/images/deep_cleaning.jpg
    - assets/images/move_in_cleaning.jpg
    - assets/images/move_out_cleaning.jpg
    - assets/images/airbnb_cleaning.jpg
    - assets/images/office_cleaning.jpg
    - assets/images/post_construction_cleaning.jpg
    - assets/images/carpet_cleaning.jpg
    - assets/images/car_standard_cleaning.jpg
    - assets/images/car_deep_cleaning.jpg
    - assets/images/truck_cabin_cleaning.jpg
    - assets/images/truck_deep_cleaning.jpg
    - assets/images/driveway_cleaning.jpg
    - assets/images/sidewalk_cleaning.jpg
    - assets/images/handyman_light.jpg
    - assets/images/handyman_fan.jpg
    - assets/images/handyman_faucet.jpg
    - assets/images/handyman_drywall.jpg
    - assets/images/toilet_repair.jpg
    - assets/images/window_repair.jpg
    - assets/images/small_painting.jpg
    - assets/images/baby_proofing.jpg
    - assets/images/shelf_mounting.jpg
    - assets/images/furniture_disassembly.jpg
    - assets/images/outdoor_furniture.jpg
    - assets/images/curtain_rod_install.jpg
    - assets/images/wall_patch_repair.jpg
    - assets/images/appliance_hookup.jpg
    - assets/images/minor_plumbing.jpg
    - assets/images/cabinet_repair.jpg
    - assets/images/window_blinds.jpg
    - assets/images/tile_caulking.jpg
    - assets/images/door_handle_fix.jpg
    - assets/images/general_handyman.jpg
    - assets/images/dryer_repair.jpg
    - assets/images/dishwasher_repair.jpg
    - assets/images/oven_repair.jpg
    - assets/images/stove_repair.jpg
    - assets/images/refrigerator_repair.jpg
    - assets/images/microwave_repair.jpg
    - assets/images/garbage_disposal.jpg
    - assets/images/ice_maker_repair.jpg
    - assets/images/rage_hood_repair.jpg
    - assets/images/small_move.jpg
    - assets/images/furniture_pickup.jpg
    - assets/images/heavy_lifting.jpg
    - assets/images/unpacking.jpg
    - assets/images/office_move.jpg
    - assets/images/storage_move.jpg
    - assets/images/furniture_assembly.jpg
    - assets/images/furniture_disassembly.jpg
    - assets/images/bed_assembly.jpg
    - assets/images/dresser_assembly.jpg
    - assets/images/table_assembly.jpg
    - assets/images/chair_assembly.jpg
    - assets/images/outdoor_furniture.jpg
    - assets/images/office_furniture.jpg
    - assets/images/lock_repair.jpg
    - assets/images/rekey_locks.jpg
    - assets/images/smart_lock_install.jpg
    - assets/images/mail_lock_replace.jpg
    - assets/images/door_handle_replace.jpg
    - assets/images/deadbolt_install.jpg
    - assets/images/broken_key_extraction.jpg
    - assets/images/flat_tire_change.jpg
    - assets/images/tire_rotation.jpg
    - assets/images/tire_installation.jpg
    - assets/images/roadside_assistance.jpg
    - assets/images/tire_delivery.jpg
    - assets/images/rim_repair.jpg
    - assets/images/lug_nut_tightening.jpg
    - assets/images/furniture_assembly.jpg
    - assets/images/bed_frame_assembly.jpg
    - assets/images/table_assembly.jpg
    - assets/images/desk_assembly.jpg
    - assets/images/sofa_assembly.jpg
    - assets/images/dresser_assembly.jpg
    - assets/images/wardrobe_assembly.jpg
    - assets/images/outdoor_furniture_assembly.jpg
    - assets/images/baby_crib_assembly.jpg
    - assets/images/furniture_disassembly.jpg
    - assets/images/clean_bathroom_fan.jpg
    - assets/images/air_filter.jpg