name: eliman
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/tire_change.jpg
    - assets/images/house_lockout.jpg
    - assets/images/lock_installation.jpg
    - assets/images/tv_mounting.jpg
    - assets/images/furniture_assembly.jpg
    - assets/images/packing.jpg
    - assets/images/washer_repair.jpg
    - assets/images/full_apartment_move.jpg
    - assets/images/car_lockout.jpg
    - assets/images/standard_cleaning.jpg
    - assets/images/deep_cleaning.jpg
    - assets/images/move_in_cleaning.jpg
    - assets/images/move_out_cleaning.jpg
    - assets/images/airbnb_cleaning.jpg
    - assets/images/office_cleaning.jpg
    - assets/images/post_construction_cleaning.jpg
    - assets/images/carpet_cleaning.jpg
    - assets/images/car_standard_cleaning.jpg
    - assets/images/car_deep_cleaning.jpg
    - assets/images/truck_cabin_cleaning.jpg
    - assets/images/truck_deep_cleaning.jpg
    - assets/images/driveway_cleaning.jpg
    - assets/images/sidewalk_cleaning.jpg
